### ISSUE TITLE
constructStringWrappingPlugin Race Condition on NTFS

### ISSUE THREAD

**Issue by TydVirTaal** [cubing/cubing.js#138]
## The Issue

Running "make dev" using WSL on Windows 10 results in the following error: 

![image](https://user-images.githubusercontent.com/52967253/131223351-f07b19b7-35dc-411d-9d48-64714cbfa3de.png)

The code responsible (with some minor changes for debugging) is here:
![image](https://user-images.githubusercontent.com/52967253/131223378-6fc7c5df-7e0b-491a-921f-81c82db4276b.png)
_screenshot from /script/build/main.js_

My debugging shows that "contents" is coming back undefined on line 89 because readFile is throwing an error indicating "no such file or directory". 

We know the directory is there, and so the leading theory (courtesy of Tomas) is that multiple workers are trying to access it at once. 

## Possible Solutions

If multithreading/async processing is required, Tomas suggests using temp files as a solution. Node does not natively support a "mktemp" equilvalent, although it does offer ["mkdtemp"](https://nodejs.org/api/fs.html#fs_fspromises_mkdtemp_prefix_options). Thus this solution can be achieved through 2 means:
1) Using an npm module like [node-temp](https://github.com/bruce/node-temp) to create temp files. This introduces additional dependencies, which may not be desirable.
2) Using Node's "mkdtemp" to create temporary directories wherein files can be placed. Cleanup can then be done with [fsPromises.rmdir()](https://nodejs.org/api/fs.html#fs_fspromises_rmdir_path_options). Rmdir could also be used to replace "rm -rf" in other parts of /script/build/main.js to remove some Windows compatibility conflicts.

This list is obviously non-exhaustive, and Lucas may well have a better idea of how to go about this.

**Comment by lgarron** [comment]
This definitely happens on other platforms as well.

I don't know when I'll have time to get to this, but we will definitely need this workaround for a few months at the very least.

I certainly wouldn't mind a cleanup here to do more robust file handling, or (ideally) avoid writing to the filesystem as much as possible.

**Comment by TydVirTaal** [comment]
Here's some code which _seems_ to have fixed the issue. It begins from line 86 of script/build/main.js, the first thing in the "else" clause.

I would have published a draft PR, but need to head out now and am just struggling to this new branch into the fork I've created :P 

Posting the code here so long for comment in case it warrants any.

`function attemptWriteWorkerInsideGenerated() {
              // Based on "Waiting for Things with setTimeout" https://www.sitepoint.com/delay-sleep-pause-wait/
              // keeps attempting to write to src/cubing/search/worker-inside-generated-string.js until successful
              // try{} runs the usual readFile/writeFile code
              // catch{} catches an error, and then re-runs this function with a 20ms timeout using setTimeout()
              try {
                readFile(
                  "src/cubing/search/worker-inside-generated.js",
                  "utf8",
                  (_, contents) => {
                    writeFile(
                      "src/cubing/search/worker-inside-generated-string.js",
                      `export const workerSource = "${contents
                        .replace(/\\/g, "\\\\")
                        .replace(/"/g, '\\"')
                        .replace(/\n/g, "\\n")}";`,
                      async () => {
                        await execPromise(
                          "rm -f src/cubing/search/worker-inside-generated.js",
                        );
                        console.log("updated worker-inside-generated-string.js");
                        resolve();
                      },
                    );
                  },
                );
              } catch (err) {
                console.log(err); // No console output on error - not sure why this is? Did we just not get here? 
                setTimeout(attemptWriteWorkerInsideGenerated, 20); // 20ms is arbitrarily selected
              };
            };
            attemptWriteWorkerInsideGenerated(); // run the function`

**Comment by lgarron** [comment]
Alright, sorry for the trouble. I dug into this quite a bit and tried to implement the cleanest thing I could.

Sorry to to use that over your PR, but would you mind checking if `make dev` and `make build` on `main` are more robust for you now?

**Comment by TydVirTaal** [comment]
No worries at all! Will experiment with make dev in the next 24h or so :D

**Comment by TydVirTaal** [comment]
Confirming it works - issue can remain closed
