### ISSUE TITLE
Hint stickers are sometimes not moving

### ISSUE THREAD

**Issue by lgarron** [cubing/cubing.js#146]
**To Reproduce**

1. Go to https://alpha.twizzle.net/edit/?alg=r+U2+x+r+U2+r+U2+r%27+U2+l+U2+r%27+U2+r+U2+r%27+U2+r%27&puzzle=4x4x4&experimental-stickering=OLL&experimental-setup-anchor=end
2. Scrub through the first U2 slowly.

Some hint stickers are not moving:

![unnamed-1](https://user-images.githubusercontent.com/248078/133183854-07b48a71-4930-4411-9133-9cbdb2627b10.png)

**Expected behavior**

All the hint stickers for `U` are moving.

**Browser:**
Chrome 93.0.4577.63
macOS 10.15.7

**Comment by rokicki** [comment]
This should be fixed with commit 63b0a55b83963f68410bb117a2e481052a07e086.
