### ISSUE TITLE
Example code tries to import `parseAlg`, but `parseAlg` is never exported.

### ISSUE THREAD

**Issue by 7ombie** [cubing/cubing.js#153]
On [`js.cubing.net/cubing`][1], there is a section named **JavaScript features**. The section contains an example HTML document with some inline JS code. The first line of that code looks like this:

``` js
import { parseAlg } from "https://cdn.cubing.net/esm/cubing/alg";
```

This fails, as there is no export named `parseAlg`.

Looking through the source with DevTools, I found an export named `Alg` which seemed like an obvious candidate for a renamed variable, so tried that. It still failed, but this time it was the call to `Alg` that failed, complaining that `Alg` can not be instantiated without `new`, so I added `new` and everything seems to work now. The result looks like this:

``` js
import { Alg } from "https://cdn.cubing.net/esm/cubing/alg";
import { TwistyPlayer } from "https://cdn.cubing.net/esm/cubing/twisty";

const player = new TwistyPlayer({
  puzzle: "4x4x4",
  alg: new Alg("R U R'"),
  hintFacelets: "none",
  backView: "top-right",
  background: "none"
});

document.body.appendChild(player);

// You can also change parameters after you've constructed the player:
player.backView = "side-by-side";
```

Note: I've omitted the HTML from the example, but it's the same as before, obviously.

[1]: https://js.cubing.net/cubing

**Comment by lgarron** [comment]
This is resolved.
