### ISSUE TITLE
3x3x3 JSON center orientation is incompatible with PG3D 

### ISSUE THREAD

**Issue by lgarron** [cubing/cubing.js#158]
**To Reproduce**

1. Go to https://experiments.cubing.net/cubing.js/twisty/mkbhd.html 
2. Run in the JS console: `document.querySelector("twisty-player").visualization = "PG3D"`

The center orientations flip around when E centers are moved.

**Expected behavior**
Center orientations don't jump.

Ideally, the 3x3x3 JSON and PG would create consistent center orientations in their definitions.

**Comment by rokicki** [comment]
Resolved with commit aa0eaf5332a4eefbcc2f79f51e1a876ec3e83222 where we rewrote the default cubie orientation code in puzzle geometry.
