### ISSUE TITLE
Add support for Xiaomi "Smart Magic Cube"

### ISSUE THREAD

**Issue by alastaira** [cubing/cubing.js#16]
Hi, I've recently acquired a bluetooth cube described as a Xiaomi Smart Magic Cube. Product link is https://uk.banggood.com/Newest-Version-XIAOMI-Original-Bluetooth-Magic-Cube-Smart-Gateway-Linkage-3x3x3-Square-Magnetic-Cube-Puzzle-Science-Education-Toy-Gift-p-1586342.html - it seems to be a more recent version of the Giiker.

It works with an Android app called "Mi Smart Magic Cube" which can be downloaded from the manufacturer at http://app.xiaomi.com/download/918392 however, unfortunately it doesn't seem to be recognised by cubing (or "Supercube" or other third party apps) - I guess because the properties/protocol of the BLE service differ from other cubes. 

I'd love to use the cubing API with it - in the absence of any documentation, I'm wondering how I can help add support for this type of cube?

**Comment by lgarron** [comment]
This cube actually uses the same protocol as the GiiKER cube, but unfortunately it doesn't advertise a device name.

The following *should* work:

- Don't tun the cube
- Go to https://bluetooth.cubing.net/
- Click "Connect" two times and reject both times.
- Click "Connect a third time". This should now show *all* devices around you (a352ae484256b3b590f4cf01bce4bcac5c0a7244).
- Wait for the list to slow down growth.
- Do a turn on the cube.

This should allow you to identify the cube and connect.

Unfortunately, I don't know how to support anything more convenient, as Xiaomi seems to have made it hard to filter for this device in the prompt. :-/

**Comment by alastaira** [comment]
Ah, that's brilliant - thankyou so much! I was fooled by the fact it doesn't seem to advertise either a device name or the services available, so my scanner was failing to find it. But you're absolutely correct - if you manually force a connection to the correct MAC address it works great. :)
