### ISSUE TITLE
canvas resize issue

### ISSUE THREAD

**Issue by ticklemepierce** [cubing/cubing.js#173]
**To Reproduce**
I'm implementing twisty-puzzle on a site I'm working on and noticed that when I change the puzzle being rendered, it frequently results in a stretched image.  I have tracked the issue down to https://github.com/cubing/cubing.js/blob/main/src/cubing/twisty/views/3D/Twisty3DVantage.ts#L173

The stretch is because the canvas ends up with the same height/width instead of the ratio.

**Expected behavior**
The height should not change to match the width dimension.

**Browser:**
- OS: [e.g. Windows 11, iOS 8.1]
- Browser [e.g. Chrome, Safari]

(Also let us know your version of `npm` or a link to your project if applicable.)

**Screenshots**
If applicable, please add screenshots to help explain your problem!

![image](https://user-images.githubusercontent.com/8229937/154545506-6e0be0dc-c7b9-48e5-a44c-a31367b72289.png)

**Comment by lgarron** [comment]
Thanks, that is definitely a typo!

**Comment by lgarron** [comment]
For the record, the line at the time was:

https://github.com/cubing/cubing.js/blob/c9c1f3486c7ca5a689123c50fc6afa2e1ad17710/src/cubing/twisty/views/3D/Twisty3DVantage.ts#L173

**Comment by lgarron** [comment]
Alright, please try `v0.25.7`!

**Comment by lgarron** [comment]
Out of curiosity, are you creating a lot of players / how?

I believe this should only affect the third player onward, which is probably why no one has noticed it so far.

**Comment by ticklemepierce** [comment]
> Out of curiosity, are you creating a lot of players / how?
> 
> I believe this should only affect the third player onward, which is probably why no one has noticed it so far.

I'm not trying to create any new ones, but I am changing the properties a bunch.  However I'm using react and haven't debugged to see if I'm getting unintended repaints from that.  It does seem to be impacting the third change and on though, so I believe you are correct on that

**Comment by ticklemepierce** [comment]
It does seem to be fixed now!

**Comment by lgarron** [comment]
> I'm not trying to create any new ones, but I am changing the properties a bunch. However I'm using react and haven't debugged to see if I'm getting unintended rerenders from that. It does seem to be impacting the third change and on though, so I believe you are correct on that

Hmm, that does sound like React is re-rendering way too often, which is disconcerting. It's probably assuming a full re-instantiation is cheap, which... it kind of is, but I wouldn't recommend it. (Animation performance will certainly be lower on some platforms due to the shared renderer.)

I stay away from React for reasons like this, but I'd be interested to debug that as well.

**Comment by ticklemepierce** [comment]
> > I'm not trying to create any new ones, but I am changing the properties a bunch. However I'm using react and haven't debugged to see if I'm getting unintended rerenders from that. It does seem to be impacting the third change and on though, so I believe you are correct on that
> 
> Hmm, that does sound like React is re-rendering way too often, which is disconcerting. It's probably assuming a full re-instantiation is cheap, which... it kind of is, but I wouldn't recommend it. (Animation performance will certainly be lower on some platforms due to the shared renderer.)
> 
> I stay away from React for reasons like this, but I'd be interested to debug that as well.

Well it led me to a refactor (to be fair, project is in early stages so code is very spaghetti still) to separate the state out better.  Now even if I roll back version I don't get the resize issue.  So my code is better now and a bug has been patched in this project, so win-win really.
