### ISSUE TITLE
When switching puzzles, unneeded cut sliders don't disappear

### ISSUE THREAD

**Issue by rokicki** [cubing/cubing.js#181]
**To Reproduce**

1. Go to twizzle explorer/7x7x7
2. Open cut editor
3. Switch to 3x3x3 by picking the puzzle from the puzzle dropdown
4. The cut panel shows more than one face cut slider.  (The cube is properly rendered.)

**Expected behavior**
All the extra unnecessary face cut sliders should be removed.

Chrome.  MacOS Catalina.

![image](https://user-images.githubusercontent.com/1631691/161649216-a301b139-d4b9-488c-ba59-22f7aa84886b.png)

**Comment by lgarron** [comment]
I originally had code for this, will have to fix it up.

The sliders also don't always match the puzzle description order, I should fix that at the same time.

**Comment by lgarron** [comment]
> The sliders also don't always match the puzzle description order, I should fix that at the same time.

Specifically, switching from 5x5x5 go 7x7x7 used to show this:
<img width="286" alt="Screen Shot 2022-04-04 at 18 59 26" src="https://user-images.githubusercontent.com/248078/161664314-042d856e-5d55-49c6-bfc2-418ea2c6234f.png">

Now it shows this:
<img width="294" alt="Screen Shot 2022-04-04 at 18 59 16" src="https://user-images.githubusercontent.com/248078/161664335-d44db71d-1498-4deb-9eb8-379ec3cd2b9d.png">
