### ISSUE TITLE
Default on first visit should be to show the alg panel, not the cut editor panel.

### ISSUE THREAD

**Issue by rokicki** [cubing/cubing.js#183]
**To Reproduce**

1.  Check out the twizzle-explorer-side-panel-tabs branch.
2. Make dev.
3. Go to http://localhost:3333/alpha.twizzle.net/explore/
4. Observe that the cut panel is displayed.

**Expected behavior**
By default, the cut panel should be hidden and the algorithm panel should be displayed.

Chrome; MacOS Catalina.

**Screenshots**
If applicable, please add screenshots to help explain your problem!

**Comment by lgarron** [comment]
Thanks for filing!

I changed the default for the branch, if you need to do this at point it should be as simple as moving the `hidden` attribute to the cut panel instead.
