### ISSUE TITLE
Three.js Integration

### ISSUE THREAD

**Issue by debater-coder** [cubing/cubing.js#190]
**Is your feature request related to a problem? Please describe.**
I'm working on a project where I need to embed a Rubik's cube in a three.js environment, and I want to be able to "send" moves to the cube, based on user interaction and other factors. I also need to have control of when re-renders or updates happen, and have them in sync with the render loop.

**Describe the solution you'd like**
I would like a class or some other abstraction, which I can use to render a puzzle from cubing.js, in a three.js scene.

**Describe alternatives you've considered**
I have tried to make my own implementation of a rubik's cube in three.js but cubing.js clearly has a much wider variety of twisty puzzles and features. I have also tried to use the `<twisty-player>` tag but it simply does not meet my requirements.

I am willing to help implement this feature and I have experience using three.js and es2020 javascript. I do not know typescript that well, and I may need help navigating your codebase.

**Comment by lgarron** [comment]
So, the good news is that we use `three.js` under the hood (for now). But there are issues with having a formal API to access it.

I can certainly give you workarounds for now, but just accessing the raw `three.js` objects probably also won't do what you want. Could I ask you to describe in more detail what controls you need, and what your constraints are for the render loop?

**Comment by debater-coder** [comment]
So ideally I would want to be able to call some method that takes in an algorithm, and have the cube execute that algorithm. A hypothetical API for this could be something like:

```js
cube.send(new alg.Alg("R U R' U R U2 R'"))
```

For the render loop, I just want to have a method that I could call in the render loop to tell it to update. For example something like:

```js
const render = () => {
    requestAnimationFrame(render)


    cube.update()
    // ... (update everything else)

    renderer.render(scene, camera)
}
```

**Comment by lgarron** [comment]
> ```js
> cube.send(new alg.Alg("R U R' U R U2 R'"))
> ```

How close does this get?

```html
<script type="module">
  import "https://cdn.cubing.net/js/cubing/twisty";
  const player = document.querySelector("twisty-player");
  player.alg = "R U R' U R U2 R'";
  player.play();
</script>

<twisty-player id="main"></twisty-player>
```

Right now there's no direct way to access the 3D objects, but that's mostly because no one has asked — I can add an experimental call to `TwistyPlayer` to make the `three.js` scene and puzzle objects available.

--------

> ```js
> const render = () => {
>     requestAnimationFrame(render)
> 
> 
>     cube.update()
>     // ... (update everything else)
> 
>     renderer.render(scene, camera)
> }
> ```

For this, I'd love to provide something like `cube.update()` as in your example, but unfortunately we have to deal with code loading tradeoffs that require us to make such an update call asynchronous — with no guarantee that it can return within milliseconds. (That said, it will *usually* have no overhead once all the relevant code has loaded, assuming you are not changing the puzzle or the alg constantly).

For this, is it important that you control `requestAnimationFrame`, or would it be sufficient for the player to send you a callback every time there is a visible puzzle update for rendering (based on its own `requestAnimationFrame` listener)?

**Comment by debater-coder** [comment]
> How close does this get?

It dosen't really fulfill my requirements as I do need to embed the cube in a three.js scene with other objects. I would really appreciate it if I could get direct access to the three.js objects.

> Is it important that you control requestAnimationFrame, or would it be sufficient for the player to send you a callback every time there is a visible puzzle update for rendering (based on its own requestAnimationFrame listener)?

After a lot of reconsideration, I've decided that it should be fine for the puzzle to update asynchronously. Before, I was in a situation where I could not have any visual updates without an explicit call, but this should be fine now.

**Comment by lgarron** [comment]
> It dosen't really fulfill my requirements as I do need to embed the cube in a three.js scene with other objects. I would really appreciate it if I could get direct access to the three.js objects.
> 

Right, would the approach above work if you also had something like` twistyPlayer.getCurrentTwistyThreeJSObject(): Promise<Object3D | null>`?

> After a lot of reconsideration, I've decided that it should be fine for the puzzle to update asynchronously. Before, I was in a situation where I could not have any visual updates without an explicit call, but this should be fine now.

Okay, sounds like we should be able to do something useful there. Would it help to have a callback for every time the puzzle has changed, though?

**Comment by debater-coder** [comment]
> Right, would the approach above work if you also had something like twistyPlayer.getCurrentTwistyThreeJSObject(): Promise<Object3D | null>?

I think that is pretty much what I am after. I should be able to just add that object into the scene.

> Okay, sounds like we should be able to do something useful there. Would it help to have a callback for every time the puzzle has changed, though?

Yes, that would be helpful because I would have to call the above method again, to have it update in my scene, right?

**Comment by debater-coder** [comment]
Does `twistyPlayer.getCurrentTwistyThreeJSObject(): Promise<Object3D | null>` return a 'snapshot' of the current object, or a reference to it?

**Comment by lgarron** [comment]
> Would `twistyPlayer.getCurrentTwistyThreeJSObject(): Promise<Object3D | null>` return a promise for the 'snapshot' of the current object, or a promise to a reference to it?

A reference.

Could you try `cubing@v0.26.6`? You should now be able to do this:

```js
import { TwistyPlayer } from "cubing/twisty";

const player = document.body.appendChild(
  new TwistyPlayer({
    alg: "[U', R] [U, R'] [R, U'] [R', U]",
    puzzle: "megaminx",
    hintFacelets: "none",
  }),
);
player.style.height = "3.5em"; // Hack to show only the control panel.
const puzzle3D = await player.experimentalCurrentThreeJSPuzzleObject(() => {
  // This callback will be called when the puzzle needs to be re-rendered.
});

// Add `puzzle3D` to a `three.js` scene.
```

For example:
https://codepen.io/lgarron/pen/vYRGQwj?editors=0010

**Comment by debater-coder** [comment]
Thank you, I've been able to add the puzzle to the scene. There is one problem though; when I change the puzzle to 3x3x3, two of the colours are an indistinguishable shade of yellow.
![image](https://user-images.githubusercontent.com/52619668/178105144-fff1caf1-c6b0-45c0-a8ca-0d010b5d0b3b.png)

The side that is supposed to be orange shows up as yellow.

The repository with this issue is here:
https://github.com/debater-coder/studious-octo-sniffle

Here is the relevant code:
```js
const player = document.body.appendChild(
      new TwistyPlayer({
        alg: "R U R' U' R' F R2 U' R' U' R U R' F'",
        puzzle: "3x3x3",
        hintFacelets: "none",
      }),
    );

    player.style.visibility = "hidden"

    player.experimentalCurrentThreeJSPuzzleObject(() => {}).then((puzzle3d) => {
      this.scene.add(puzzle3d)
      this.gui.add(player, "play")
      player.play();
    })
```

**Comment by debater-coder** [comment]
Actually, nevermind, I believe that was because of my output encoding:
```js
    renderer.physicallyCorrectLights = true;
    renderer.outputEncoding = THREE.sRGBEncoding;
    renderer.toneMapping = THREE.CineonToneMapping;
    renderer.toneMappingExposure = 1.75;
    renderer.shadowMap.enabled = true;
    renderer.shadowMap.type = THREE.PCFSoftShadowMap;
```

For now I will turn that off, but is there anyway I can change the colour scheme to work with it?

**Comment by debater-coder** [comment]
Sorry for reopening this, but I've had trouble "sending" moves to the cube. I've tried your code where you set `player.alg` and then you call `player.play()` but if you change `player.alg` then the player resets.

What I'd like is to be able to "send" one move, and then have it run on the cube, then later, possibly based on user input, have another move run, but preserve the state of the previous move. Using the hypothetical API from earlier:
```js
player.send("R")
// ...
player.send("U")

// End result is same as sending `player.send("R U")`
```

**Comment by debater-coder** [comment]
In Twizzle, I remember there being an input option where you could choose to have input from keyboard or Bluetooth. I wonder if there could be an API for specifying a custom input source, so that you can programmatically send moves to the cube.

**Comment by lgarron** [comment]
> Sorry for reopening this, but I've had trouble "sending" moves to the cube. I've tried your code where you set `player.alg` and then you call `player.play()` but if you change `player.alg` then the player resets.

In that case, you probably want:

```js
player.experimentalAddMove("R")
```

With the current, code this will always jump to the latest added move, but that will be smoother in the future.

**Comment by lgarron** [comment]
> Sorry for reopening this, but I've had trouble "sending" moves to the cube. I've tried your code where you set `player.alg` and then you call `player.play()` but if you change `player.alg` then the player resets.

In that case, you probably want:

```js
player.experimentalAddMove("R")
```

With the current, code this will always jump to the latest added move, but that will be smoother in the future.

**Comment by debater-coder** [comment]
Thank you, I've tested that and at least in my code it appears to animate smoothly between the states. I'm closing this issue, now but I'll let you know if I experience any issues with `cubing.js`. It's an excellent library and if there is anyway I can contribute, even if its documentation, please let me know.

**Comment by debater-coder** [comment]
Also, in the source code that method appears to be deprecated?
```js
```

**Comment by debater-coder** [comment]
Also, in the source code that method appears to be deprecated?
```js
 /** @deprecated */
  async experimentalCurrentThreeJSPuzzleObject(
    puzzleChangeCallback?: () => void,
  ): Promise<Object3D>
```

**Comment by lgarron** [comment]
> Also, in the source code that method appears to be deprecated?

Yep! Anything with the prefix `experimental` is going to go away some day, so I tend to mark those as deprecated. That said, the whole point of making a public experimental method like this is to see if the experimental version works well enough, in which case we can adapt it into a non-experimental method some day. But to know if it works well, we need use cases like yours. :-P

There's no guarantee we'll be sticking with `three.js` forever, but it's like to be the case in the foreseeable future. VR and similar use cases also need an API like this, so I'd say you're fairly safe using it (but of course no promises until `v1.0`).
