### ISSUE TITLE
experiments/bluetooth won't connect

### ISSUE THREAD

**Issue by anicolao** [cubing/cubing.js#196]
**To Reproduce**

1. Go to 'https://experiments.cubing.net/cubing.js/bluetooth/'
2. Click on 'Connect'
3. Button changes to read 'Connected. Keyboard Input' and is greyed out.

**Expected behavior**
The site should enable connecting a bluetooth cube.

**Browser:**
Google Chrome	104.0.5112.79 (Official Build) (arm64) 
Revision	3cf3e8c8a07d104b9e1260c910efb8f383285dc5-refs/branch-heads/5112@{#1307}
OS	macOS Version 12.3.1 (Build 21E258)
JavaScript	V8 10.4.132.20

**Comment by lgarron** [comment]
Thanks, this should be fixed now! 😄

**Comment by anicolao** [comment]
Maybe this fix is not deployed but I don't see a behaviour change on the live site.

**Comment by lgarron** [comment]
Our server sometimes serves overly long caching headers. Does it work after clearing the cache or in another different browser profile?

**Comment by anicolao** [comment]
It's connecting now, and naturally exhibiting the duplicate of my other issue (infinite moves). So this one is closed indeed.
