### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './scramble' is not defined by "exports"

### ISSUE THREAD

**Issue by Nash171** [cubing/cubing.js#198]
getting an error when I try to use library in a node project

`import { randomScrambleForEvent } from "cubing/scramble";`

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './scramble' is not defined by "exports" in [project_folder]\node_modules\cubing\package.json

library version - 0.28.2
node version - 16.13.0

**Comment by lgarron** [comment]
Hmm, this is definitely defined in the published package: https://unpkg.com/browse/cubing@0.28.2/package.json

Could you share more information about your project/setup?

**Comment by Nash171** [comment]
@lgarron Hi Garron,
Yes I noticed that, I tried cubing-app-template project and its working for me.
Seems something wrong with the ts compilation in my setup :slightly_frowning_face:

I have setup a repo to recreate this issue
https://github.com/Nash171/cubing-test.git

and this a gitpod snapshot
https://gitpod.io#snapshot/973b7ff6-d10b-49d2-a81e-493677c76a56

Thanks

**Comment by lgarron** [comment]
> @lgarron Hi Garron, Yes I noticed that, I tried cubing-app-template project and its working for me. Seems something wrong with the ts compilation in my setup 🙁
> 
> I have setup a repo to recreate this issue https://github.com/Nash171/cubing-test.git
> 
> and this a gitpod snapshot https://gitpod.io#snapshot/973b7ff6-d10b-49d2-a81e-493677c76a56
> 
> Thanks

Ah, it looks like this is because your `dist/index.js` has this line:

```js
const scramble_1 = require("cubing/scramble");
```

We only support ESM, so this import doesn't resolve using CJS/`require`. There are a lot of issues with CommonJS compat, so we are unlikely to ever support it.

Would you be able to switch your project to using ES modules / do you need any help?

**Comment by Nash171** [comment]
Oh Thanks!

I added `"type": "module"` line to package.json file
and changed module configuration in tsconfig.json file to
`"module": "ES6"`

https://github.com/Nash171/cubing-test/commit/b785db790bf7a23f1c529f7a3d0aa82d27510db4

now its working, do I did the correct change?
will this configuration fail compilation after adding other libraries?

gitpod workspace - https://nash171-cubingtest-f2w7112s3e2.ws-us60.gitpod.io

Thanks

**Comment by lgarron** [comment]
Yep, that should work!
`node` and browsers have supported ES modules for quite a while, and just about every maintained library should be properly compatible, although I can't promise there won't be edge cases — feel free to file another issue if you think it's `cubing.js` related. I'll close this for now.

**Comment by Nash171** [comment]
Sure, Thanks for the help and for this great library :slightly_smiling_face:

**Comment by lgarron** [comment]
Alright, closing for now!
