### ISSUE TITLE
Can't run `make test-spec` in codespaces

### ISSUE THREAD

**Issue by lgarron** [cubing/cubing.js#199]
`web-test-runner` errors:

```shell
❌ The CHROME_PATH environment variable must be set to a Chrome/Chromium executable no older than Chrome stable.
```

We can almost certainly install Chrome (we do it for Puppeteer!) where `web-test-runner` can find it, we just need to figure out how.

**Comment by lgarron** [comment]
Still not sure why `web-test-runner` is unable to find Puppeteer's Chrome installation: https://modern-web.dev/guides/test-runner/browsers/

This also doesn't fix it:

```shell
npm i --save-dev @web/test-runner-playwright
```

**Comment by lgarron** [comment]
Aha! I need to pass `--playwright` on the commandline rather than `web-test-runner.config.js`!

Unfortunately we still have Puppeteer-based tests. But we can use Puppeteer for now.

**Comment by lgarron** [comment]
Looks like `@web/test-runner-puppeteer` installs a *second* instance of Chrome in its own `node_modules`. 😕

**Comment by anicolao** [comment]
This is possibly fixed by https://github.com/cubing/cubing.js/pull/204

**Comment by lgarron** [comment]
Resolved by recent refactoring.
