### ISSUE TITLE
Can't figure out how to create a KPuzzle as a client

### ISSUE THREAD

**Issue by anicolao** [cubing/cubing.js#220]
### Steps to reproduce the issue

I'd like to be able to create new `KPuzzle` instances in node. In the browser my workaround is:
```
const twistyPlayer = new TwistyPlayer();
const kp: KPuzzle = await twistyPlayer.experimentalModel.kpuzzle.get();
```
but in node this doesn't work because there is no shadow DOM (besides being super ugly).

`KPuzzle`'s constructor wants a puzzle definition, and I can't figure out where to import `cube3x3x3KPuzzleDefinition` from as a client of the library.

### Observed behaviour

The documentation contains no examples of creating `KPuzzle` objects.

### Expected behaviour

Ideally there would at least be a page that enumerates all the importable modules and their exports, even if these have no documentation, so that I could grep for the things I can't find and figure out where they are. Perhaps there is a node/js/npm way to do this that I don't know.

### Environment

Node on macos

**Comment by lgarron** [comment]
Yeah, this recently moved. For now, the place you'll want is:

https://github.com/cubing/cubing.js/blob/2f84aa58f799457ac63b4ae6e43ba98cf87d2f49/src/cubing/puzzles/PuzzleLoader.ts#L14

For example:


```ts
import { cube3x3x3 } from "cubing/puzzles";

await cube3x3x3.kpuzzle()
```

**Comment by anicolao** [comment]
For my use cases, async is really inconvenient. Is there a sync option? What I am currently doing as a workaround is:
```
const def = cube3x3x3KPuzzleDefinition;
const kp: KPuzzle = new KPuzzle(def);
```
where `cube3x3x3KPuzzleDefinition` is a copy of the original file located in `$lib/third_party/hack.ts`. This hack could be quite long lasting as this definition will basically never change.

**Comment by lgarron** [comment]
> Is there a sync option?

Unfortunately not. We want it to make it easy to use lots of puzzles, without paying for puzzles you don't use, so the only choice is for us to use `Promise`s and dynamic imports as much as possible. It used to be possible to get the 3x3x3 definition synchronously, but I've purposely taken that out of the API because I want to avoid special-casing 3x3x3, and I don't think we'll go back.

If you know which definitions you need ahead of time, can you load them at the top level of your app before anything else runs, and store them in globals?

Otherwise, could you describe in more detail what inconveniences you're running into?

**Comment by anicolao** [comment]
I need `KPuzzle` instances for tests, and since I don't really know how to program in typescript nor how all the various different testrunner choices work, I don't know how to create these instances in an async way. I do know that if I make a particular test async it doesn't work for reasons I do not understand. A specific example is:

```
        async function validateTransform({ from, to, afterRotations }: TestCase) {
		const def = cube3x3x3KPuzzleDefinition;
		const kp: KPuzzle = new KPuzzle(def);
		const startState = kp.startState();
		const state = afterRotations ? startState.applyAlg(afterRotations) : startState;
		const newMove = GANCube.colorToFaceMove(from, state.stateData); // TypeError only when async
		expect(newMove).to.equal(to);
	}

	// after an X rotation , ULFRBD <- FLDRUB
	const faceCases = [
		{ face: 0x06, originalFace: 'F', expectedFace: 'U' },
		{ face: 0x0c, originalFace: 'L', expectedFace: 'L' },
		{ face: 0x09, originalFace: 'D', expectedFace: 'F' },
		{ face: 0x03, originalFace: 'R', expectedFace: 'R' },
		{ face: 0x05, originalFace: "R'", expectedFace: "R'" },
		{ face: 0x00, originalFace: 'U', expectedFace: 'B' },
		{ face: 0x0f, originalFace: 'B', expectedFace: 'D' },
		{ face: 0x26, originalFace: 'z', expectedFace: 'z' }
	];
	for (const { face, originalFace, expectedFace } of faceCases) {
		it(`should not touch '${face}' moves`, () => {
			validateTransform({ from: face, to: originalFace });
		});

		it(`should modify '${face}' to '${expectedFace}' moves with x rotation`, () => {
			validateTransform({
				from: face,
				to: expectedFace,
				afterRotations: new Alg('x')
			});
		});
	}
```

If `validateTransform` is made `async`, then the `GANCube.colorToFaceMove` line throws `TypeError: cannot read properties of undefined`. Why making the function `async` without in any way modifying its body would change its behaviour is beyond me.

**Comment by lgarron** [comment]
If you're using a similar testing framework, you should be able to make your test functions async. We use this:

[expect(await sum.get()).to.equal(14);](https://github.com/cubing/cubing.js/blob/1a0d874e5ae4efe74af2e98c3ade7d77fe0dbd14/src/cubing/twisty/model/props/TwistyProp.spec.ts#L22)

If you really want each individual test to be synchronous, you can calculate `kpuzzle` outside the test. But I find it easier to just use `async` code when needed:

```ts
import { cube3x3x3 } from "../../../puzzles";
import { randomScrambleForEvent } from "../../../scramble";

const kpuzzle = await cube3x3x3.kpuzzle();

describe("kpuzzle tests", async () => {

  // could also get `kpuzzle` here (or inside the test, for that matter).

  it("can compute", async () => {
    expect(
      (await randomScrambleForEvent("333")).experimentalNumChildAlgNodes(),
    ).is.greaterThan(15);

    expect(
      kpuzzle.algToTransformation(
        "R U R' F' U2 L' U' L F U2",
      ).isIdentityTransformation(),
    ).to.be.true;
  });
});
```

**Comment by anicolao** [comment]
Moving the async up a level instead of having it on `validateTransform` directly did fix my problem and enable me to create the kpuzzle in an async way and have the tests pass! Like I said, I don't know how to program in typescript yet so this fix/workaround is very welcome, thanks.

As for what test framework I am using, it's `vitest`+`chai`+`Wallaby.js`, a configuration that is approximately 100x faster than `@web/testrunner` though it is true that Wallaby.js is proprietary (free for OSS development). If fast tooling is a goal, I am aware of no faster code coverage+test runner+debugger option than Wallaby.js.

**Comment by lgarron** [comment]
> If fast tooling is a goal, I am aware of no faster code coverage+test runner+debugger option than Wallaby.js.

It is! But it's also important that there is no friction for testing in browser environments. Wallaby doesn't seem to advertise that?

**Comment by lgarron** [comment]
Marking as resolved.

**Comment by anicolao** [comment]
@lgarron it should be possible to configure Wallaby to integrate with the testing setup in this project, I just haven't attempted it. The [reference for their configuration](https://wallabyjs.com/docs/config/reference.html) certainly implies to me that you could use `@web/testrunner` as the test runner and test in a browser environment. Even if that doesn't work, at the cost of some new dependency for testing like `mocha` or `vite`, you could have `make test-spec` run things one way and the editor integration run tests with Wallaby to speed development.

It's so much faster that it is indescribable. I personally have a love-hate relationship with vscode and its ecosystem, and I only use it for languages I don't know like typescript where I've definitely written < 30kloc of code, but this one tool could cause me to use it even for languages I know well where I've written far more code than that.
