### ISSUE TITLE
Attempting to use Wallaby.js, but magic for importing 'three' is beyond me

### ISSUE THREAD

**Issue by anicolao** [cubing/cubing.js#221]
### Steps to reproduce the issue

I was trying to see if Wallaby.js could be used on this project. The following wallaby.cjs config file "almost" works:
```
module.exports = function (wallaby) {
    return {
      env: {
        kind: 'chrome',
      },
      files: [
        'src/**/*.ts',
        { pattern: 'src/**/*.spec.ts', ignore: true }
      ],

      tests: [
        'src/**/*.spec.ts'
      ],

      testFramework: 'mocha'
    };
  };
```
There seems to be a potential bug in `src/sites/experiments.cubing.net/cubing.js/spec/binary/index.ts` where `stub` is referenced without guards: 
```
diff --git a/src/sites/experiments.cubing.net/cubing.js/spec/binary/index.ts b/src/sites/experiments.cubing.net/cubing.js/spec/binary/index.ts
index def8054d..f7488bc1 100644
--- a/src/sites/experiments.cubing.net/cubing.js/spec/binary/index.ts
+++ b/src/sites/experiments.cubing.net/cubing.js/spec/binary/index.ts
@@ -28,7 +28,7 @@ function entry(
   val.colSpan = colSpan;
 }
 
-{
+if (stub) {
   const [, tbody] = newTable(stub);
 
   const tr1 = tbody.appendChild(document.createElement("tr"));
```

Once the setup is done, set the `Wallaby.js` configuration file to `wallaby.cjs` and look at its output console in vscode.

### Observed behaviour

After doing that there are a bunch of errors in the wallaby console of the form:

```
​​[Error] Runtime error: TypeError: Failed to resolve module specifier "three". Relative references must start with either "/", "./", or "../".​​

​​and then finally

[Error] Runtime error: TypeError: Failed to resolve module specifier '@esm-bundle/chai'​​
​​[Error]     at http://localhost:55605/src/test/chai-workarounds/chai.js?1663156638852&wallabyFileId=2:6:51​​
```

It looks like these are both "special" imports that I have no hope of understanding where/how they are configured so that chrome can find them.

### Expected behaviour

Ideally there is a simple missed step like `make build` or something that would magically make wallaby's instance of chrome work for this codebase.

### Environment

MacOS + vscode

**Comment by lgarron** [comment]
Thanks!

Unfortunately, it looks like Wallaby's licensing is a bit restrictive: https://wallabyjs.com/oss/

> ## What projects can I use the free Wallaby Open Source license with?
> 
> Open source projects that:
>
> - Are publicly available on [GitHub](https://github.com/) with an open source license.
> - Do not provide paid versions of open source software or any commercial services around the open source project (e.g. paid support, consulting, etc).

As we build up more of Twizzle, I want us to be able to support free servers for the community.
I'm paying for any servers myself right now, but I want to build something self-sustainable, which may be incompatible with the second bullet. So it looks like this is not an option for us. :-/

**Comment by lgarron** [comment]
As far as I'm aware, the fastest way to run `.spec.ts` files directly would be `bun`: https://bun.sh/
One nice step would be to enable that.

I'd also love to move away from Mocha and Chai to something else (with proper ESM builds and based around explicit imports rather than funky globals), but I don't know of great options yet.

**Comment by anicolao** [comment]
@lgarron as far as I know, bun still runs all the tests. What makes Wallaby.js fast is it knows the coverage for the lines you are editing, and runs only those tests that apply. In my tiny project where there are over 600 tests to exercise the bluetooth code, the tests take about 4s in `vitest`. Nonetheless, my test status updates as I type because Wallaby never executes all 600 tests at once. 

Nonetheless, I mentioned that the tool is proprietary, because I knew that might be an obstacle. I suspsect their second bullet is to stop large operations from using their stuff freely on OSS, for example to prevent vscode from being developed with free Wallaby licenses when it's clearly part of a large moneymaking venture. A cubing library with donations or small contributions to keep a few servers afloat would hardly attract their attention.

In any event for my own cubing site, I am able to easily host it within the free tier of firebase, which covers its backend, serving, auth, and user data storage all for free. I imagine that basically every roux solver with a bluetooth cube could use it every day and I still won't exceed the free tier...

**Comment by lgarron** [comment]
Okay, I looked into it some more, and `uvu` was the most promising.
However, it doesn't work nicely with` web-test-runner`, so `asdgf` might be the best alternative: https://github.com/modernweb-dev/web/issues/1156#issuecomment-972600741

Chai-based assertions still have issues in `bun`, but there's probably a reasonable workaround for that as well.
