### ISSUE TITLE
Can't figure out new simplify options

### ISSUE THREAD

**Issue by anicolao** [cubing/cubing.js#231]
### Steps to reproduce the issue

I'm trying to replicate the behaviour of my old code:
```
remaining = new Alg(inverted).simplify({ collapseMoves: true, quantumMoveOrder: () => 4 });
```

### Observed behaviour

I attempted two choices:
```
remaining = new Alg(inverted).simplify({
			cancel: {
				directional: 'any-direction',
				puzzleSpecificModWrap: 'canonical-centered'
			}
		});
```
and the simpler `cancel: true`, but neither replicates the prior behaviour.

### Expected behaviour

I should be able to find documentation or examples on how to transition from the old API to the new API. I didn't look very hard, but I failed to find anything helpful.

### Environment

all platforms

**Comment by anicolao** [comment]
I eventually figured out the incantation:
```
remaining = new Alg(inverted).experimentalSimplify({
			cancel: {
				directional: 'any-direction',
				puzzleSpecificModWrap: 'canonical-centered'
			},
			puzzleLoader: cube3x3x3
		});
```

**Comment by lgarron** [comment]
Yep, that should work, glad you found it.

Are you developing if TypeScript? That should at least help determine valid values for such inputs.

For now, though, I'll see about adding some examples to https://experiments.cubing.net/cubing.js-typedoc/classes/alg.Alg.html#simplify (and therefore also the comments in the published `d.ts` files).

**Comment by anicolao** [comment]
I am developing in typescript - the only issue surfaced for the original attempt was that `simplify` was marked deprecated. After I changed it to `experimentalSimplify` the problem persisted because `puzzleSpecificModWrap` is accepted whether or not `puzzleLoader` is specified, and it took me trying to write failing unit tests which had the same inputs as my production code for me to eventually realize I was missing the `puzzleLoader` option.

**Comment by lgarron** [comment]
> For now, though, I'll see about adding some examples to https://experiments.cubing.net/cubing.js-typedoc/classes/alg.Alg.html#simplify (and therefore also the comments in the published `.d.ts` files).

Doen in 145d0a7a3271a71fd1051c871bb170560561a24b.
