### ISSUE TITLE
[Twizzle issue] Invalid addtion of commutators

### ISSUE THREAD

**Issue by nbwzx** [cubing/cubing.js#235]
### Steps to reproduce the issue

1. Go to https://alpha.twizzle.net/
2. In the moves input, put [R,U][R,U], we can see that it is invalid.
3. However, this alg is valid in https://alg.cubing.net/

### Observed behaviour

[R,U][R,U] is invalid.

### Expected behaviour

It can display properly, just like in https://alg.cubing.net/

### Browser & operating system

Chrome

### 🖼 Screenshots

![alpha twizzle net_edit_](https://user-images.githubusercontent.com/55343466/196096584-13874a47-c863-4d23-936c-85bfc276130c.png)
![alg cubing net__alg=%5BR,U%5D%5BR,U%5D](https://user-images.githubusercontent.com/55343466/196096544-e744a1c1-3e5b-4104-8fd9-9673e032d6d7.png)

**Comment by lgarron** [comment]
This is intentional — `cubing/alg` requires spaces between all alg nodes. I do not expect to revisit this decision.

`alg.cubing.net` needs to support its own historical syntax, but if you click the Twizzle link at https://alg.cubing.net/?alg=%5BR,_U%5D%5BR,_U%5D you'll end up at https://alpha.twizzle.net/edit/?alg=%5BR%2C+U%5D+%5BR%2C+U%5D with `[R, U] [R, U]`.

**Comment by nbwzx** [comment]
Okey, I understand. Thank you.

**Comment by nbwzx** [comment]
I wonder if it is possible to add spaces between all alg nodes automatically or simply give some hints if users' input is not so 'standard'. Admittedly, I felt confused when this alg is invalid in https://alpha.twizzle.net/ in the beginning.

**Comment by lgarron** [comment]
> I wonder if it is possible to add spaces between all alg nodes automatically or simply give some hints if users' input is not so 'standard'.

Yeah, I definitely want some heuristics in place for common formatting errors. It's important that the text field doesn't automatically *accept* anything that wouldn't be accepted by `cubing.js` anywhere else (else it would set the expectation that algs are not safe to copy and paste between different apps), but it should be possible to surface better error messages from the alg parser and indexer:

- Insufficient spacing.
- Incorrect `'`-like marks.
- Which moves are invalid for the current puzzle.
