### ISSUE TITLE
2x2x2 Definition has only 7 pieces?

### ISSUE THREAD

**Issue by AshleyF** [cubing/cubing.js#24]
Curious why 222 has only 7 pieces?

https://github.com/cubing/kpuzzle.js/blob/master/src/puzzle_definitions.ts#L6

**Comment by lgarron** [comment]
2x2x2 now has 8 pieces everywhere in `cubing.js` (hardcoded JSON and `puzzle-geometry`):

https://github.com/cubing/cubing.js/blob/a4e0e5968659030a6b96e7ff894537f75079248a/src/cubing/puzzles/implementations/2x2x2/2x2x2.kpuzzle.json_.ts#L6
