### ISSUE TITLE
Can no longer generate random scrambles

### ISSUE THREAD

**Issue by anicolao** [cubing/cubing.js#240]
### Steps to reproduce the issue

I recently updated all my dependencies to the latest and now when I deploy to production I can no longer generate random scrambles. This works in dev serving.

### Observed behaviour

In the console I am seeing:
```
Uncaught ReferenceError: document is not defined
    at preload-helper-aa6bc0ce.js:1:28
    at preload-helper-aa6bc0ce.js:1:143
Scramble-f4281b28.js:2 Could not instantiate module worker (this may happen in Firefox, or when using Parcel). Falling back to string worker. Error: module instantiation timeout
    at Scramble-f4281b28.js:2:796
_n @ Scramble-f4281b28.js:2
593665bf-ffd6-4a50-8a64-e4a72e7bdf1f:3878 random333Scramble: 140ms
```

### Expected behaviour

Scrambles should load. I will need help figuring out how to debug this as I really have no concept of what's going on with the async loading.

### Environment

MacOS Chrome

**Comment by anicolao** [comment]
hmm. This problem mysteriously stopped reproducing for me :(

**Comment by lgarron** [comment]
Sounds like this might have been an issue with your bundler or web server?

**Comment by anicolao** [comment]
I didn't change anything about my configuration, which is static hosting by firebase. So it's a bit mysterious that it happened and then fixed itself :(

**Comment by lgarron** [comment]
> So it's a bit mysterious that it happened and then fixed itself :(

My best guess would be inconsistent caching headers and/or cache invalidation on the server.
