### ISSUE TITLE
[Feature request] Make picture mode gutters controllable

### ISSUE THREAD

**Issue by anicolao** [cubing/cubing.js#246]
### Goal

I was trying to write the bandaged cube for MagicVince's visualization, and thought I could do it with the 'picture' stickering, but the code introduces gutters whether I want them or not. Even hacking on what I thought were the right variables in the source didn't seem to eliminate them.

### Possible solution

In picture mode there should be an option to make the texture have no boundaries, so that the user can control the edge-to-edge appearance of the cubies. In the most perfect universe there would also be a place in the sprite for the textures that sit between layers (there are 8 more of those aside from the 6 already needed for the exterior of the cube).

### Alternatives

A possible alternative is to have a way to pass in a function that generates the surface for each facelet.

**Comment by lgarron** [comment]
> In picture mode there should be an option to make the texture have no boundaries, so that the user can control the edge-to-edge appearance of the cubies

I avoided adding this before, because I didn't need it. This is a pretty good use case, though. Would it be alright if this required JS? For example:

```ts
twistyPlayer.stickerScale = 1;
```

**Comment by anicolao** [comment]
For my purposes that's fine because I already am using JS to create and configure the player. 

It would also be great to have control of the facelet hint sticker positioning and camera FoV, for other use cases though.

**Comment by lgarron** [comment]
Alright, this is available in `cubing@v0.31.7`:

```html
<script type="module">
  import { TwistyPlayer } from "https://cdn.cubing.net/js/cubing/twisty";

  const player = document.body.appendChild(new TwistyPlayer());
  player.experimentalFaceletScale = 1;
</script>
```

> It would also be great to have control of the facelet hint sticker positioning and camera FoV, for other use cases though.

**Comment by lgarron** [comment]
Closing this out, since it's been available for over a week. Please comment if you have further questions or issues!

**Comment by anicolao** [comment]
I've been distracted with other things for a while but I will attempt to put this to use for the bandaged cube visualization sometime soon.
