### ISSUE TITLE
[Feature request] First layer colours for cubeLikeStickeringMask

### ISSUE THREAD

**Issue by jgouly** [cubing/cubing.js#272]
### Goal

I'm using cubing.js with 2x2 and would like to highlight the D layer stickers or corners (for showing first layer solutions).

### Possible solution

Add a D Layer corner option to cubeLikeStickeringMask.

**Comment by lgarron** [comment]
Does the F2L stickering work for you?

https://codepen.io/lgarron/pen/YzJbVNN?editors=1000

Or do you also need LL pieces to show as dim?

**Comment by jgouly** [comment]
Ah nice, didn't think to try that.

Dimming, *might* be a bit nicer because it can help you one-look since you can see what happens to the other pieces.

**Comment by lgarron** [comment]
In that case, try:

```html
<twisty-player puzzle="2x2x2" experimental-stickering-mask-orbits="CORNERS:DDDD----" alg="R U R' U R U2' R'"></twisty-player>
```

`experimental-stickering-mask-orbits` will probably removed in favor of a replacement at some point, but as long as you're okay with vendoring your code (or updating it some day) you should be fine.

**Comment by jgouly** [comment]
Great, thanks!
