### ISSUE TITLE
[Feature request] Custom Color Schemes

### ISSUE THREAD

**Issue by trexrush** [cubing/cubing.js#276]
### Goal

Id like to be able to add a custom color scheme to a visualization (for example, Black instead of Grey on Megaminx)

### Possible solution

Im imagining an optional parameter to `TwistyPlayer` where you can define a color schema

**Comment by lgarron** [comment]
I'm gonna deduplicate this into #157. It's something I want to do eventually, but it's one of those things that sounds deceptively simple but super hard to design correctly.
