### ISSUE TITLE
[cubing.js issue] Support annoying single quote

### ISSUE THREAD

**Issue by jgouly** [cubing/cubing.js#285]
### Steps to reproduce the issue

Lots of people post algs with ’ instead of '. This makes it impossible to paste into twizzle!

### Observed behaviour

twizzle errors because it doesn't recognise ’

### Expected behaviour

Parse the alg as a '

### Environment

None

**Comment by lgarron** [comment]
Based on previous discussions, I think I would be happiest with this compromise:

1. Establish which quotes are actually common in the wild.
2. Implement a paste listener in `<twisty-alg-editor>` and rewrite those quotes in non-comment parts of the pasted text.

I got stuck implementing this in https://github.com/cubing/cubing.js/compare/fix-quotes-on-paste but I'd love to see a PR that implements it reliably.

**Comment by lgarron** [comment]
I sunk an evening into this, and I think I finally have an implementation I'm okay with: https://github.com/cubing/cubing.js/commit/695d369e64d3e271ec8278fa3358ee922df3d75e

Going to leave this issue open for a bit while I shake out the edge cases that I haven't thought of yet.

**Comment by lgarron** [comment]
This has been stable enough — we can follow up in future issues.
