### ISSUE TITLE
[cubing.js issue] Not compatible with nextjs

### ISSUE THREAD

**Issue by bryanlundberg** [cubing/cubing.js#298]
### Steps to reproduce the issue

1. npx create-next-app@latest
2. npm install cubing
3. replace default page with a basic usage

```
"use client";
import { useState, useEffect } from "react";
import { randomScrambleForEvent } from "cubing/scramble";

export default function App() {
  const [scrambleString, setScrambleString] = useState("");

  function genScramble() {
    randomScrambleForEvent("sq1").then((scramble) => {
      const scrambleStr = scramble.toString();
      setScrambleString(scrambleStr);
    });
  }
  useEffect(() => genScramble(), []);

  return (
    <>
      <button onClick={() => genScramble()}>genScramble</button>
      <p>{scrambleString}</p>
    </>
  );
}
```

### Observed behaviour

Error: Javascript and Typescript versions.

### 🖼 Screenshots

![image](https://github.com/cubing/cubing.js/assets/119996547/ba664e10-b486-4b0e-bea4-2e1215c3ab29)

### Expected behaviour

Click the button a generate a scramble.

### Environment

node 20

### Additional info

same code using vite app, works fine.

**Comment by lgarron** [comment]
This is due to some unfortunate interactions between ecosystem tools.

At the moment we can't use that line, and taking it out seems to prevent Next from trying to locate it. I'll remove it from the published code for now.

**Comment by lgarron** [comment]
Alright, please try with `v0.43.8`. Thanks for the report!
