### ISSUE TITLE
[cubing.js issue] throws error with ClassListManager.ts and Twistyprop.ts

### ISSUE THREAD

**Issue by GhostShadow0316** [cubing/cubing.js#305]
### Steps to reproduce the issue

I created a cube timer [project](https://github.com/GhostShadow0316/HAC-Cube/blob/master/js/timer.js)
and I want to show scrambles

### Observed behaviour

but today when I'm updating my project
I see these error massages and I don't know how to fix it

### 🖼 Screenshots

![brave_E3k23pR6dh](https://github.com/cubing/cubing.js/assets/94322065/aa5d9772-a017-4b6c-a5bc-942f1f98d416)

### Expected behaviour

no error

### Environment

brave browser

### Additional info

here's my [code](https://github.com/GhostShadow0316/HAC-Cube/blob/master/js/timer.js)

**Comment by lgarron** [comment]
I've had a chance to look into this, and this stems from:

```js
Object.defineProperty(Object.prototype, 'renameKey', {
    value: function (oldName, newName) {
        if (oldName === newName) { return this; }
       if (this.hasOwnProperty(oldName)) {
           this[newName] = this[oldName];
           delete this[oldName];
       }
       return this;
    },
    enumerable: false, // this is actually the default
});
```

We could (and probably should) update the `cubing.js` code to avoid relying on `in` returning an iterator with the right elements, but this definition may also be causing other issues for you. It doesn't seem you're using this function, but if you truly have to declare it on the prototype I recommend replacing it with something like:

```js
Object.defineProperty(Object.prototype, 'renameKey', {
    value: function (oldName, newName) {
        if (oldName === newName) { return this; }
       if (this.hasOwnProperty(oldName)) {
           this[newName] = this[oldName];
           delete this[oldName];
       }
       return this;
    },
    enumerable: false, // this is actually the default
});
```

But if you can avoid defining properties on the prototypes of the core JS objects then you'll run into these issues less frequently.

**Comment by GhostShadow0316** [comment]
it worked!!!
thank you very much

**Comment by lgarron** [comment]
I took a lot at working around programs that do this, and concluded that it's impractical at this time. `three.js` has a bunch of built-in assumptions, so we can't work around this in `cubing.js` alone.
