### ISSUE TITLE
megaminx colours cant be distinguisible

### ISSUE THREAD

**Issue by kelpyguy** [cubing/cubing.js#306]
### Goal

easier for megaminx distinguish colours beige and white 

### Possible solution

change the beige colour tobe moredistinguishiable

### Alternatives

allow custom colour schemes

**Comment by lgarron** [comment]
This was the original color:
 
![Screenshot 2023-12-30 at 01 52 44](https://github.com/cubing/cubing.js/assets/248078/272f40e7-1e5d-40da-ba87-c8ddb5ee20c9)

This is what it was showing as:

![Screenshot 2023-12-30 at 01 52 25](https://github.com/cubing/cubing.js/assets/248078/460e663b-9cb6-4446-92d2-03ea831a12a2)

I've tweaked it a bit more to increase contrast until we tackle color spaces (#308) and overall accessibility:

![Screenshot 2023-12-30 at 01 52 11](https://github.com/cubing/cubing.js/assets/248078/cc821370-68e0-4b52-8631-1292446b30c4)
