### ISSUE TITLE
All puzzles never moves.

### ISSUE THREAD

**Issue by Abdullah6576** [cubing/cubing.js#311]
### Steps to reproduce the issue

1. Go to alpha.twizzle.net 2. Click on editor and explorer. 3. Click on all puzzles.

### Observed behaviour

I have clicked on all of these puzzles but they never turns.

### Expected behaviour

They all should move.

### Browser & operating system

Opera GX

**Comment by lgarron** [comment]
Indeed, we can't do much with this report. Are you able to identify errors or share any screenshots?

**Comment by lgarron** [comment]
I was also able to install Opera GX on an Android device. Twizzle works without issue for me.
