### ISSUE TITLE
Nextjs experimentalAddMove applies move twice

### ISSUE THREAD

**Issue by chrisgloom** [cubing/cubing.js#313]
### Steps to reproduce the issue

sorry for the messy code had commented out a lot to challenge my assumptions. 

Using experimentalAddMove in a react component in a nextjs project, the move happens twice for some reason, F is F2, R is R2...not sure why. Open to it being entirely my fault haha. Maybe something to do with it being in a react component?

```javascript
const Twisty = ({ algString, latestMove }) => {
  console.log(algString)
  const twistyPlayerRef: TwistyPlayer = useRef<TwistyPlayer>(null)

  if (twistyPlayerRef.current && latestMove) {
    // testing adding a move
    twistyPlayerRef.current.experimentalAddMove('F')
  }

  useEffect(() => {
    // Accessing the twisty-player instance through ref
    if (twistyPlayerRef.current) {
      //   window.cube = twistyPlayerRef.current
      // Perform actions on the twisty-player instance
      twistyPlayerRef.current.experimentalModel.playingInfo.set({
        playing: true,
        loop: false,
      })
      demoSpinCamera(twistyPlayerRef.current, 0.5)
      // console.log()
    }
  }, [])
  // todo: only pass in new moves after the initial setup alg

  return (
    <>
      <twisty-player
        control-panel="bottom-row"
        background="none"
        ref={twistyPlayerRef}
        // experimental-setup-alg={algString}
      ></twisty-player>
    </>
  )
}
```

### Observed behaviour

The intended move is applied twice to the cube

### 🖼 Screenshots

<img width="575" alt="image" src="https://github.com/cubing/cubing.js/assets/15905991/3aebb056-9a63-46c2-adb5-f1e537e30872">

### Expected behaviour

Just applied once

### Environment

nextjs blog project

**Comment by chrisgloom** [comment]
hmm, attaching it to the window and calling the function in the console just does the move once as expected. These are some react shenanigans it seems.

**Comment by lgarron** [comment]
Glad to hear you figured it out!
