### ISSUE TITLE
Svelte / SvelteKit Module Worker Errors

### ISSUE THREAD

**Issue by LiamKrenn** [cubing/cubing.js#327]
### Steps to reproduce the issue

1. Create brand new Svelte or SvelteKit project
2. Install `cubing` npm package
3. Basic code for scramble generation:
```
<script lang="ts">
	import { randomScrambleForEvent } from "cubing/scramble";
	import { onMount } from "svelte";

	onMount(async () => {
		console.log(await randomScrambleForEvent("333"))
	});
</script>
```

### Observed behaviour

Server side error:
```
The file does not exist at "C:/Users/Liam/Documents/Coden/ScrambleGen/node_modules/.vite/deps/search-worker-entry.js" which is in the optimize deps directory. The dependency might be incompatible with the dep optimizer. Try adding it to `optimizeDeps.exclude`.
The file does not exist at "C:/Users/Liam/Documents/Coden/ScrambleGen/node_modules/.vite/deps/search-worker-entry.js?worker_file&type=module" which is in the optimize deps directory. The dependency might be incompatible with the dep optimizer. Try adding it to `optimizeDeps.exclude`.
The file does not exist at "C:/Users/Liam/Documents/Coden/ScrambleGen/node_modules/.vite/deps/search-worker-entry.js" which is in the optimize deps directory. The dependency might be incompatible with the dep optimizer. Try adding it to `optimizeDeps.exclude`.
```

Client side error:
```
Module worker instantiation using `import.meta.resolve(…) failed, falling back.
Module worker instantiation using inline `new URL(…, import.meta.url)` failed, falling back.
Module worker instantiation using `new URL(…, import.meta.url)` failed, falling back.
Module worker instantiation using the `esbuild` workaround failed, falling back.
Uncaught ReferenceError: document is not defined
Uncaught (in promise) Error: Module worker instantiation failed. There are no more fallbacks available. If you are using Firefox, please update to version 114 or later.
```

### 🖼 Screenshots

![Error log browser console](https://github.com/cubing/cubing.js/assets/71632691/861eccae-4aca-40fb-8bff-e4957f9795fd)

### Expected behaviour

Scramble logged - no error, since #323 mentions svelte compatibility.

### Environment

Using Chrome (since error log mentions firefox)

### Additional info

Tried with brand new svelte and sveltekit projects, and after some researching also tried adding following into the vite config:
```
worker: {
    format: 'es'
}
```
and
```
build: { target: 'es2020' },
optimizeDeps: { esbuildOptions: { target: "es2020" } }
```

also tried [vitejs/vite#14499 (comment)](https://github.com/vitejs/vite/issues/14499#issuecomment-1740267849)

**Comment by lgarron** [comment]
Apologies for not replying earlier. I spent quite some time looking at this trying to get you a good answer and kind of failed. I think SvelteKit is just broken for our web worker code, despite the extreme time I have invested in making it as compatible as possible. It's probably because they're using item.

I'll comment with more details when I have time to look into it again.

**Comment by lgarron** [comment]
I think Svelte has fixed this. I was able to generate scrambles in a fresh project.
