### ISSUE TITLE
[cubing.js issue] typo docs: decivingly - deceivingly

### ISSUE THREAD

**Issue by bryanlundberg** [cubing/cubing.js#330]
### Steps to reproduce the issue

Its on this file: line 98
https://github.com/cubing/cubing.js/blob/main/src/docs/js.cubing.net/cubing/alg/index.html

### Observed behaviour

`decivingly`

### Expected behaviour

`deceivingly`

### Environment

does not apply

**Comment by lgarron** [comment]
Thanks for the report! Glad people are looking closely enough at the code to notice this. 😅
