### ISSUE TITLE
twisty-alg-viewer

### ISSUE THREAD

**Issue by BakiTANRISEVEN** [cubing/cubing.js#335]
### Goal

jstwisty-alg-viewer

### Possible solution

Hello;
![cube3](https://github.com/user-attachments/assets/c2428046-5cb4-4947-8192-156e02d40704)

As you can see in the picture, I used a method like this to show the algorithm.

`<`twisty-player id="kup1" alg="F2 U' R' L F2 R L' U' F2" viewer-link="none" background="none" visualization="PG3D">`<`/twisty-player>      `<`twisty-alg-viewer for="kup1">`<`/twisty-alg-viewer>

It would be better to show the algorithm in `<`twisty-player>`<`/twisty-player>. So it would be better to integrate (include) it in `<`twisty-player>`<`/twisty-player>.

**Comment by lgarron** [comment]
This feature is a long-term goal, but there are several UX challenges I need to sup

**Comment by BakiTANRISEVEN** [comment]
Thank you Mr Lucas. Good luck.
