### ISSUE TITLE
[Twizzle issue] Icosahedron color scheme hurts to look at.

### ISSUE THREAD

**Issue by Lord0fTheCubes** [cubing/cubing.js#336]
### Steps to reproduce the issue

Open Twizzle and click on any icosahedral puzzle

### Observed behaviour

The color scheme is horrific. There are many weird shades of blue, purple, pink, and green, most of which are extremely similar to one another, and staple colors of twisty puzzles (white, yellow, red, etc.) are completely missing. I conducted a series of polls on the FTO Discord server and we decided that this is the new unofficial standard color scheme for icosahedral puzzles. Please fix this. The current icosahedron color scheme is such an eyesore that it is genuinely the main reason why I don't solve icosahedral puzzles in Twizzle.
![1320 x 760 - PNG (7)](https://github.com/user-attachments/assets/5d1094df-b03b-4d30-8e0c-130438c0ca70)

### 🖼 Screenshots

I cannot vibe with this.
![custom-2  (7)](https://github.com/user-attachments/assets/96872929-9381-468b-ace9-6310d559fcb2)

### Expected behaviour

I expected the icosahedron color scheme to look like literally anything other than it currently does (preferably the color scheme I linked above).

### Browser & operating system

Chrome (idk what version) on Mac OS

### Additional info

Here are some of the names for the icosahedral puzzles listed on the site:
Icosahedron 2 = Regular Astrominx
Icosahedron 3 = Regular Astrominx + Big Chop
Icosahedron moving faces = Icosaminx
Here are some more that you could include to broaden the default puzzle selection in Twizzle:
Potential puzzles that could be added (sorry I'm getting a little carried away with this whole icosahedron thing)
Radiolarian 2: i f 0.7453559925
Radiolarian 3: i f 0.7
Astrominx (not regular astrominx, just astrominx): i v 0.275

**Comment by JupiLogy** [comment]
Could you confirm the colours that are meant to be opposite each other? Is white opposite purple-grey??

**Comment by lgarron** [comment]
I'd definitely love to update the colors.

Are you able to provide more context on the provided screenshot, or examples of it in action? I certainly like that (dark) green and white are in the traditional positions, but I'm a little concerned about three shades of lavender and there are fewer symmetries and similarities with other puzzles than possible.

**Comment by Lord0fTheCubes** [comment]
Sorry for the late replies.

This color scheme doesn't follow the trend of similar colors being opposite. The faces of an icosahedron can be thought of as five groups of four faces, with each group following the geometry of a tetrahedron. For example, the monochrome colors are all in one group, and they don't touch each other at all, even diagonally. The same doesn't apply to color schemes where similar colors are opposite; if white and light gray are opposite one another, there is nowhere to put dark gray and black so that they aren't diagonal or adjacent to white. So yes, white is intended to be opposite light purple. If you prefer a color scheme in which similar colors are opposite, here's an alternate color scheme.
![lotc's_new](https://github.com/user-attachments/assets/425e793d-8f29-4e26-832e-83c587a9a587)

I don't have any examples of this color scheme on a puzzle, as it was only recently created. For background information on why the colors were placed where they were, read the above. The FTO server thread voted on what colors would be used. There is only one shade of lavender, one pink, one fuchsia, and one purple. The alternate color scheme above has many more similarities with the octahedron and icosahedron color schemes, if you'd prefer that.

**Comment by lgarron** [comment]
@Lord0fTheCubes Apologies for the delay, as you might imagine I've been rather occupied. Thanks for filing this issue, it made it easy for me to pick up the context again!

I've implemented and deployed the following:
![clipboard](https://github.com/user-attachments/assets/ba6a08cb-bd5e-4859-953f-7b6ad4216c24)

Could I ask you to consult with other people who were interested in a color scheme change and let me know you and their feedback? Thanks!

**Comment by Lord0fTheCubes** [comment]
Thank you so much! I'm waiting to hear back from the icosahedron thread on Discord, but I love the new color scheme. Replacing black with charcoal was a good idea, to avoid it being the same color as the puzzle body. The only nitpick I have about this is that you used a darker shade of blue on the dodecahedron color scheme, and icosahedra would benefit from using that blue to avoid any possible confusion with the lighter shade blue.

And while I'm on the topic, both DianSheng and DaYan used a dark gray on their FTOs rather than light gray, but the gray used in Twizzle is still light. Idk how hard it is to change color schemes, so I hope I'm not asking too much.

Thanks for everything!

**Comment by lgarron** [comment]
> The only nitpick I have about this is that you used a darker shade of blue on the dodecahedron color scheme, and icosahedra would benefit from using that blue to avoid any possible confusion with the lighter shade blue.

Good idea, done!

> And while I'm on the topic, both DianSheng and DaYan used a dark gray on their FTOs rather than light gray, but the gray used in Twizzle is still light. Idk how hard it is to change color schemes, so I hope I'm not asking too much.

Good point. I've introduced `MediumGray` for this, since there's only one gray on FTO (rather than two like on icosa). That gives more contrast while allowing the luminance to still be on the "brighter" side like the faces.

**Comment by Lord0fTheCubes** [comment]
Both of the updated colors look good to me. Thank you so much for making them differentiable!

**Comment by lgarron** [comment]
Glad to hear it! Gonna close out this issue for now, feel free to file new issues if anything comes to mind.
