### ISSUE TITLE
Consecutive commutators cause parsing problems.

### ISSUE THREAD

**Issue by lgarron** [cubing/cubing.js#5]
[U2 [R2 U2 L2, U2]]
    [[U2 R2 U2, L2] U2]'

**Comment by rokicki** [comment]
Can you explain how the above strings *should* be parsed, because to me they don't look valid?

**Comment by lgarron** [comment]
Hmm, those do have a typo. This works:

https://alg.cubing.net/?alg=%5BU2,_%5BR2_U2_L2,_U2%5D%5D_%5B%5BU2_R2_U2,_L2%5D,_U2%5D-

I'll close this unless I run into it again.
