### ISSUE TITLE
Pauses (dots) don't work in twizzle

### ISSUE THREAD

**Issue by rokicki** [cubing/cubing.js#7]
Putting a dot (a short pause) in an algorithm in twizzle does not behave properly.  This is because the MoveIndexer returns a BlockMove, and a Pause is not a BlockMove.  A lot of signatures need to be changed to permit the move indexer to return a Unit (likely), and then the call sites need to check to see if what was returned was actually a BlockMove or a non-state-change algorithm element such as a pause.

**Comment by lgarron** [comment]
`AlgIndexer` is now based on `AnimatedLeafUnit`, and I believe all implementations will handle pauses.
