### ISSUE TITLE
Renaming faces

### ISSUE THREAD

**Issue by lgarron** [cubing/cubing.js#81]
Right now, Megaminx and FTO have `BF`/`BB` as a face names as a workaround for the fact that we can't use `B` without prefix collisions. That is, a Megaminx with edge turning would have ambiguous moves like `BR` using our current automatic move name assignment.

While moving to twizzle.net, I'd like us to switch to permanent names for these faces, ideally `B` instead of `BF`/`BB`. At the same time, I'd also like to rename the remaining arbitrary face names, at least on dodecahedron (icosahedron might just be a lost cause).

I've implemented new face names behind a flag at https://github.com/cubing/cubing.js/commit/7fd3d1f2807ed814cc5fe66857e8494a28a40541 so I can use them for some applications (where I just need Megaminx face turns). But we need to figure out a good way to handle this without causing move name collisions.

**Comment by rokicki** [comment]
I've added a few notation mappers to puzzle geometry, and we'll add more.  This is the current showstopper for a WCA-compatible release.

**Comment by lgarron** [comment]
We have notation mappers that work well enough for now. This is a layer *on top* of KPuzzle definitions, which isn't always great, but it's not a blocker for Twizzle.
