### ISSUE TITLE
Shared renderers are broken.

### ISSUE THREAD

**Issue by lgarron** [cubing/cubing.js#90]
For example, try animating or reorienting the view for puzzles at https://experiments.cubing.net/cubing.js/twisty/attributes.html

Some of the viewers will go blank, and the FPS is super low.
Previously, shared renderers were fairly reliable and had good FPS at low resolutions.

I'll dig into this at some point, but I could use help [pinpointing](https://git-scm.com/docs/git-bisect) where this went bad.

**Comment by preethamrn** [comment]
Ran git bisect and it seems like the performance issues started after this commit (https://github.com/cubing/cubing.js/commit/af97b685e192ca216fea8f5438a16d4f3717034b). I haven't gone through the code much yet but left this comment in case someone else can help pinpoint the issue.

**Comment by lgarron** [comment]
> Ran git bisect and it seems like the performance issues started after this commit ([af97b68](https://github.com/cubing/cubing.js/commit/af97b685e192ca216fea8f5438a16d4f3717034b)). I haven't gone through the code much yet but left this comment in case someone else can help pinpoint the issue.

Aha! That's a fairly plausible commit, because it interacts with the 3D objects, the DOM, and animation frames. I don't immediately see how this would affect shared renderers, but it's a useful start. Thanks for the bisection!

**Comment by lgarron** [comment]
> I think there's another issue on top of this because there are some cases where some stickers go black which doesn't happen here
> main branch:
> ![image](https://user-images.githubusercontent.com/10453269/100539235-e8ee3b80-31e9-11eb-83c9-d791995f0d42.png)
> [af97b68](https://github.com/cubing/cubing.js/commit/af97b685e192ca216fea8f5438a16d4f3717034b):
> ![image](https://user-images.githubusercontent.com/10453269/100539249-0de2ae80-31ea-11eb-83ca-8cc2686c0c5d.png)

Ah, this probably comes from making the cubie foundation opaque. I should revert that for non-picture cubes, although we'll still have to work on the z-fighting.

**Comment by lgarron** [comment]
> I should revert that for non-picture cubes

Done in 0475891c374a19d3ca0e009fdaa1df32b9487aeb.
