### ISSUE TITLE
LineComment constructor: Throw an error if the text contains a newline

### ISSUE THREAD

**Issue by lgarron** [cubing/cubing.js#97]

**Comment by sachinh19** [comment]
I would like to take a go at this one as one of my first issues on github. Can you clarify some more on what needs to be done here?

I already see an error being thrown on [this line](https://github.com/cubing/cubing.js/blob/3442d9ad4e25804e50ad47aef8f34ac7b736da12/src/cubing/alg/units/leaves/LineComment.ts#L13) in the _**LineComment**_ constructor when the **_commentText_** argument contains a newline.

**Comment by lgarron** [comment]
> I would like to take a go at this one as one of my first issues on github. Can you clarify some more on what needs to be done here?

Thanks!

> I already see an error being thrown on [this line](https://github.com/cubing/cubing.js/blob/3442d9ad4e25804e50ad47aef8f34ac7b736da12/src/cubing/alg/units/leaves/LineComment.ts#L13) in the _**LineComment**_ constructor when the **_commentText_** argument contains a newline.

Yeah, the issues I file are not always 100% in sync with what's left to do. :-P

This issue could be close, but it would be good to have a test for this:

1. Copy https://github.com/cubing/cubing.js/blob/3442d9ad4e25804e50ad47aef8f34ac7b736da12/src/cubing/alg/units/leaves/Move.spec.ts into something like `LineComment.spec.ts`.
2. Test that a newline in the comment text throws an error.
3. Test that a bunch of other stuff (e.g. text, symbols, emoji) doesn't throw errors.

Would you be up for that?

**Comment by sachinh19** [comment]
I'll give it a try, but would take a few days as the week just began and I'll be a bit busy in my day job. If its not urgent I'd like work on this.

**Comment by sachinh19** [comment]
I would also like to know if you have any guidelines for contributors, any standard steps to follow or any tests that I need to run before I create a PR?

**Comment by sachinh19** [comment]
I ran the `npm run build `and `npm run test` commands which included the format check, seemed safe to create a PR.

**Comment by sachinh19** [comment]
@lgarron can you please close this issue if the work here is completed?

**Comment by lgarron** [comment]
> @lgarron can you please close this issue if the work here is completed?

Yep, thanks!
